/**
 * global
 */
export const GLOBAL_CHANGE_PROGRESS = 'GLOBAL_CHANGE_PROGRESS'
export const GLOBAL_TOGGLE_LOGIN = 'GLOBAL_TOGGLE_LOGIN'
export const GLOBAL_TOGGLE_REGISTER = 'GLOBAL_TOGGLE_REGISTER'

export const GLOBAL_GET_CATEGORYLIST = 'GLOBAL_GET_CATEGORYLIST'
export const GLOBAL_RECEIVE_CATEGORYITEM = 'GLOBAL_RECEIVE_CATEGORYITEM'

export const GLOBAL_GET_COMMENTLIST = 'GLOBAL_GET_COMMENTLIST'
export const GLOBAL_INSERT_COMMENTITEM = 'GLOBAL_INSERT_COMMENTITEM'

/**
 * frontend
 */
export const FRONTEND_RECEIVE_ARTICLELIST = 'FRONTEND_RECEIVE_ARTICLELIST'
export const FRONTEND_RECEIVE_TRENDING = 'FRONTEND_RECEIVE_TRENDING'
export const FRONTEND_RECEIVE_ARTICLEITEM = 'FRONTEND_RECEIVE_ARTICLEITEM'

export const FRONTEND_MODIFY_LIKESTATUS = 'FRONTEND_MODIFY_LIKESTATUS'
