/**
 * global
 */
export const GLOBAL_CHANGE_PROGRESS = 'GLOBAL_CHANGE_PROGRESS'
export const GLOBAL_GET_CATEGORYLIST = 'GLOBAL_GET_CATEGORYLIST'
export const GLOBAL_RECEIVE_CATEGORYITEM = 'GLOBAL_RECEIVE_CATEGORYITEM'

/**
 * frontend
 */
export const FRONTEND_RECEIVE_ARTICLELIST = 'FRONTEND_RECEIVE_ARTICLELIST'
export const FRONTEND_RECEIVE_TRENDING = 'FRONTEND_RECEIVE_TRENDING'
